FROM golang:1.24-alpine

# Install any dependencies needed for testing
RUN apk --no-cache add postgresql-client

# Set working directory
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Command to run tests
CMD ["go", "test", "-v", "./internal/model", "./internal/parser", "./internal/database", "./internal/handler", "./swift_api/", "-short"]